---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-runtimeconditions-io-v1alpha1-runtimeconditionsprofile
  failurePolicy: Fail
  name: vruntimeconditionsprofile-v1alpha1.kb.io
  rules:
  - apiGroups:
    - runtimeconditions.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runtimeconditionsprofiles
  sideEffects: None
