apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: rc-admission-webhook
    app.kubernetes.io/managed-by: kustomize
  name: runtime-conditions-controller-manager
  namespace: runtime-conditions-system
