apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rc-admission-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rc-admission-webhook.labels" . | nindent 4 }}
